# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d133e410e1a435de7ceba9bf0cb1389c7437c4e5bdc4f7f6146cf2586b9072410e6258ab83982e7649cad16352b0f0631db5342a821881f2f822a61bfb2d7b7d

test:
  secret_key_base: e9849e9e69e05c86a441b23e2ebba3df517d393655fa1ddf6749573a5882da946ecb17499d151d8ebe08bd8ba85b1ac3e119b6e7d89842ccd3f9adb276a5d94c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
